global action_scripts := {}
global action_scripts_no_params := {}
; action_scripts.Push("alarmenable")
; action_scripts.Push("alarmstop")
; action_scripts.Push("alarmtrigger")
; action_scripts.Push("isDisconnecteddisable")
; action_scripts.Push("isDisconnectedenable")


; action_conditions.Push("needresupply")


/*
a
*/
action_scripts.Push("alarmplay")
action_scripts_no_params.Push("alarmplay")
action_scripts.Push("alarmstop")
action_scripts_no_params.Push("alarmstop")
/*
b
*/
action_scripts.Push("battlelistchangeorder")
action_scripts.Push("battlelistchangesize")
action_scripts.Push("buyitemnpc")
/*
c
*/
action_scripts.Push("capacity")
action_scripts_no_params.Push("capacity")
action_scripts.Push("chatcontains")
action_scripts.Push("cleardefaultchat")
action_scripts_no_params.Push("cleardefaultchat")
action_scripts.Push("clearserverlogchat")
action_scripts_no_params.Push("clearserverlogchat")
action_scripts.Push("clickonfollowoption")
action_scripts_no_params.Push("clickonfollowoption")
action_scripts.Push("clickonsqm")
action_scripts.Push("clickonitem")
action_scripts.Push("clickonimage")
action_scripts.Push("clickonposition")
action_scripts.Push("closebackpack")
action_scripts.Push("closecavebot")
action_scripts_no_params.Push("closecavebot")
action_scripts.Push("convertgold")
action_scripts_no_params.Push("convertgold")
action_scripts.Push("creaturesbattlelist")
action_scripts_no_params.Push("creaturesbattlelist")
action_scripts.Push("creaturesaround")
action_scripts_no_params.Push("creaturesaround")
/*
d
*/
action_scripts.Push("depositmoney")
action_scripts_no_params.Push("depositmoney")
action_scripts.Push("deposititems")
action_scripts_no_params.Push("deposititems")
action_scripts.Push("deposittostash")
action_scripts.Push("droplootonground")
action_scripts_no_params.Push("droplootonground")
action_scripts.Push("droptrash")
action_scripts_no_params.Push("droptrash")
/*
e
*/
action_scripts.Push("exitgame")
action_scripts_no_params.Push("exitgame")
/*
f
*/
action_scripts.Push("focusclient")
action_scripts_no_params.Push("focusclient")
action_scripts.Push("follow")
action_scripts.Push("forcewalkarrow")
action_scripts_no_params.Push("forcewalkarrow")
action_scripts.Push("forcewalkarrowstop")
action_scripts_no_params.Push("forcewalkarrowstop")
/*
g
*/
action_scripts.Push("getbalance")
action_scripts_no_params.Push("getbalance")
action_scripts.Push("getsetting")
action_scripts.Push("getuseroption")
action_scripts.Push("gotolabel")
/*
h
*/
action_scripts.Push("hascooldown")
/*
i
*/
action_scripts.Push("isattacking")
action_scripts_no_params.Push("isattacking")
action_scripts.Push(_IsBackpackOpenedAction.IDENTIFIER)
action_scripts.Push("isbattlelistempty")
action_scripts_no_params.Push("isbattlelistempty")
action_scripts.Push("isdisconnected")
action_scripts_no_params.Push("isdisconnected")
action_scripts.Push("isfollowing")
action_scripts_no_params.Push("isfollowing")
action_scripts.Push("islocation")
action_scripts_no_params.Push("islocation")
action_scripts.Push("isplayersbattlelistempty")
action_scripts_no_params.Push("isplayersbattlelistempty")
action_scripts.Push("itemcount")
action_scripts.Push("itemsearch") ; searchess for the item image on the entire screen, returns the amount of items found(zero if none found)
action_scripts.Push("imagesearch") ; https://trello.com/c/QieFHDgM/336-action-imagesearch
/*
j
*/
/*
k
*/
/*
l
*/
action_scripts.Push("level")
action_scripts_no_params.Push("level")
action_scripts.Push("lifepercent")
action_scripts.Push("luremode")
action_scripts.Push("luremodestop")
action_scripts_no_params.Push("luremodestop")
action_scripts.Push("luremodewalkingattack")
action_scripts_no_params.Push("luremodewalkingattack")
action_scripts.Push("luremodewalkingattackstop")
action_scripts_no_params.Push("luremodewalkingattackstop")
action_scripts.Push("log")
action_scripts.Push("lootaround")
action_scripts_no_params.Push("lootaround")
action_scripts.Push("distancelooting")
action_scripts_no_params.Push("distancelooting")
/*
m
*/
action_scripts.Push("manapercent")
action_scripts.Push("math")
action_scripts.Push("m")
action_scripts.Push("messagebox")
action_scripts.Push("minimapcenter")
action_scripts_no_params.Push("minimapcenter")
action_scripts.Push("minimapheight")
action_scripts.Push("minimapzoom")
action_scripts.Push("mousedrag")
action_scripts.Push("mousedragimage")
action_scripts.Push("mousedragimageitem")
action_scripts.Push("mousedragimageposition")
action_scripts.Push("mousedragitem")
action_scripts.Push("mousedragitemimage")
action_scripts.Push("mousedragitemposition")
action_scripts.Push("mousemove")
/*
n
*/
action_scripts.Push("notification")
action_scripts.Push("npchi") ; check if npc chat is opened, if not, say hi and wait for it to open, repeat it once if fail
action_scripts_no_params.Push("npchi")
action_scripts.Push("npctrade") ; check if npc trade is opened, if not, say hi/trade and wait for it to open, repeat it once if fail
action_scripts_no_params.Push("npctrade")
/*
o
*/
action_scripts.Push("openbackpack")
action_scripts.Push("opendepot")
action_scripts_no_params.Push("opendepot")
/*
p
*/
action_scripts.Push("presskey")
action_scripts.Push("pausemodule")
/*
q
*/
/*
r
*/
action_scripts.Push("randomnumber")
action_scripts.Push("reloadcavebot")
action_scripts_no_params.Push("reloadcavebot")
action_scripts.Push("resetsession")
action_scripts_no_params.Push("resetsession")
action_scripts.Push("reachlocation")
action_scripts.Push("runactionwaypoint")
/*
s
*/
action_scripts.Push("say")
action_scripts.Push("screenshot")
action_scripts_no_params.Push("screenshot")
action_scripts.Push("sellallitemsnpc")
action_scripts_no_params.Push("sellallitemsnpc")
action_scripts.Push("sellitemnpc")
action_scripts.Push("setlocation")
action_scripts.Push("setsetting")
action_scripts.Push("stamina")
action_scripts_no_params.Push("stamina")
action_scripts.Push("soulpoints")
action_scripts_no_params.Push("soulpoints")
/*
t
*/
action_scripts.Push("takeitemfromstash")
action_scripts.Push("targetingdisable")
action_scripts_no_params.Push("targetingdisable")
action_scripts.Push("targetingenable")
action_scripts_no_params.Push("targetingenable")
action_scripts.Push("telegrammessage")
action_scripts.Push("telegramscreenshot")

action_scripts.Push("transfergold")
action_scripts.Push("travel")

; action_scripts.Push("traytip")
action_scripts.Push("turn")
action_scripts.Push("turnchaton")
action_scripts_no_params.Push("turnchaton")
action_scripts.Push("turnchatoff")
action_scripts_no_params.Push("turnchatoff")
/*
u
*/
action_scripts.Push("useitem")
action_scripts.Push("useitemoncorpses")
action_scripts_no_params.Push("useitemoncorpses")
action_scripts.Push("usesqm")
action_scripts.Push("unpausemodule")
/*
v
*/
action_scripts.Push("variable")
action_scripts.Push("variableshowall")
action_scripts_no_params.Push("variableshowall")
/*
w
*/
action_scripts.Push("wait")
action_scripts.Push("waypointdistance")
action_scripts.Push("write")
/*
x
*/
/*
y
*/
/*
z
*/

